# Generated by Django 4.0.4 on 2022-04-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
